// src/screens/interventions/CBTReframe.js
import React, { useState } from 'react';
import { View, Text, TextInput, TouchableOpacity, StyleSheet, ScrollView, Alert, KeyboardAvoidingView, Platform, ActivityIndicator } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { theme } from '../../theme/theme';
import { postData } from '../../utils/api';

export default function CBTReframe({ navigation, route }) {
  // Pre-populated starter prompts generated by Gemma
  const starterPrompt = route.params?.starterPrompt || "I feel like a failure because I didn't finish my work today.";
  
  const [automaticThought, setAutomaticThought] = useState(starterPrompt);
  const [evidenceFor, setEvidenceFor] = useState('');
  const [evidenceAgainst, setEvidenceAgainst] = useState('');
  const [balancedThought, setBalancedThought] = useState('');
  const [loading, setLoading] = useState(false);

  const handleSave = async () => {
    if (!automaticThought || !balancedThought) {
      Alert.alert('Incomplete', 'Please fill out at least the automatic thought and balanced thought.');
      return;
    }

    setLoading(true);
    
    // Save to moodLogs as supplementary clinical data
    const payload = {
      interventionType: 'cbt_reframe',
      automaticThought,
      evidenceFor,
      evidenceAgainst,
      balancedThought,
      offlineSyncId: Date.now().toString()
    };

    const result = await postData('/mood/log', payload, 'moodLogs');
    setLoading(false);

    if (result.success) {
      Alert.alert('Saved', 'Your CBT reframe has been saved successfully.');
      navigation.goBack();
    } else {
      Alert.alert('Error', 'Could not save the CBT reframe.');
    }
  };

  return (
    <SafeAreaView style={styles.safeArea}>
      <KeyboardAvoidingView 
        style={styles.container}
        behavior={Platform.OS === 'ios' ? 'padding' : 'height'}
        keyboardVerticalOffset={Platform.OS === 'ios' ? 0 : 20}
      >
        <ScrollView contentContainerStyle={styles.scrollContent}>
          <Text style={styles.title}>CBT Reframing</Text>
          <Text style={styles.subtitle}>Challenge negative thoughts to find a balanced perspective.</Text>

          <View style={styles.card}>
            <Text style={styles.label}>1. Automatic Negative Thought</Text>
            <Text style={styles.helperText}>What is the negative thought going through your mind?</Text>
            <TextInput
              style={styles.input}
              multiline
              value={automaticThought}
              onChangeText={setAutomaticThought}
              placeholder="e.g. I am a complete failure..."
            />
          </View>

          <View style={styles.card}>
            <Text style={styles.label}>2. Evidence For the Thought</Text>
            <Text style={styles.helperText}>What facts support this thought?</Text>
            <TextInput
              style={styles.input}
              multiline
              value={evidenceFor}
              onChangeText={setEvidenceFor}
              placeholder="e.g. I made a mistake on my project..."
            />
          </View>

          <View style={styles.card}>
            <Text style={styles.label}>3. Evidence Against the Thought</Text>
            <Text style={styles.helperText}>What facts contradict this thought?</Text>
            <TextInput
              style={styles.input}
              multiline
              value={evidenceAgainst}
              onChangeText={setEvidenceAgainst}
              placeholder="e.g. I usually get good reviews, one mistake doesn't define me..."
            />
          </View>

          <View style={[styles.card, styles.balancedCard]}>
            <Text style={styles.label}>4. Balanced Alternative Thought</Text>
            <Text style={styles.helperText}>Write a more realistic, balanced perspective based on the evidence.</Text>
            <TextInput
              style={[styles.input, styles.balancedInput]}
              multiline
              value={balancedThought}
              onChangeText={setBalancedThought}
              placeholder="e.g. I made a mistake, but I am still capable and can learn from it."
            />
          </View>

          <TouchableOpacity
            style={styles.saveBtn}
            onPress={handleSave}
            accessibilityLabel="Save your reframed thought"
            disabled={loading}
          >
            {loading ? <ActivityIndicator color="#fff" /> : <Text style={styles.btnText}>Save Reframe</Text>}
          </TouchableOpacity>
        </ScrollView>
      </KeyboardAvoidingView>
    </SafeAreaView>
  );
}

const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: theme.colors.cream,
  },
  container: {
    flex: 1,
  },
  scrollContent: {
    padding: theme.spacing.xl,
    paddingBottom: theme.spacing.xxl * 2,
  },
  title: {
    fontFamily: theme.typography.display,
    fontSize: 28,
    color: theme.colors.charcoal,
    marginBottom: theme.spacing.sm,
  },
  subtitle: {
    fontFamily: theme.typography.body,
    fontSize: 16,
    color: theme.colors.warmGray,
    marginBottom: theme.spacing.xl,
  },
  card: {
    backgroundColor: theme.colors.warmWhite,
    padding: theme.spacing.lg,
    borderRadius: 16,
    marginBottom: theme.spacing.lg,
    borderWidth: 1,
    borderColor: theme.colors.softGray,
  },
  balancedCard: {
    borderColor: theme.colors.sage,
    backgroundColor: theme.colors.sageLight + '30', // adding transparency
  },
  label: {
    fontFamily: theme.typography.bodyMedium,
    fontSize: 16,
    color: theme.colors.charcoal,
    marginBottom: theme.spacing.xs,
  },
  helperText: {
    fontFamily: theme.typography.body,
    fontSize: 14,
    color: theme.colors.warmGray,
    marginBottom: theme.spacing.md,
  },
  input: {
    backgroundColor: theme.colors.cream,
    borderRadius: 12,
    padding: theme.spacing.md,
    fontFamily: theme.typography.body,
    fontSize: 15,
    minHeight: 80,
    textAlignVertical: 'top',
    borderWidth: 1,
    borderColor: theme.colors.softGray,
  },
  balancedInput: {
    borderColor: theme.colors.sageLight,
  },
  saveBtn: {
    backgroundColor: theme.colors.roseDark,
    paddingVertical: theme.spacing.lg,
    borderRadius: 12,
    alignItems: 'center',
    marginTop: theme.spacing.md,
  },
  btnText: {
    fontFamily: theme.typography.bodyMedium,
    color: theme.colors.warmWhite,
    fontSize: 16,
  }
});
